// Builder data for all 12 builders
export const builderData = {
  "ecobuilders-group": {
    id: 1,
    name: "EcoBuilders Group",
    tagline: "Building Tomorrow's Sustainable Future",
    heroImage: "https://yodezeen.com/wp-content/uploads/2025/07/YODEZEEN-Modern-Mosque-01-1024x724.jpg",
    description:
      "Leading the way in sustainable construction with innovative eco-friendly designs and green building practices.",
    completedProjects: 45,
    ongoingProjects: 8,
    yearsOfExperience: 15,
    currentProjects: [
      {
        name: "ECO SKYVIEW",
        type: "3 BHK HOMES & RETAIL",
        location: "OPP. GREEN VALLEY, SECTOR 21",
        image: "https://yodezeen.com/wp-content/uploads/2025/07/YODEZEEN-Modern-Mosque-01-1024x724.jpg",
        status: "Under Construction",
      },
      {
        name: "ECO PARKWEST",
        type: "2/3 BHK HOMES & RETAIL",
        location: "NEAR ECO PARK, SECTOR 18",
        image: "https://yodezeen.com/wp-content/uploads/2025/03/WhatsApp-Image-2025-03-18-at-17.17.21-1024x731.jpeg",
        status: "Launching Soon",
      },
      {
        name: "THE ECO TOWERS",
        type: "4/5 BHK CRAFTED RESIDENCES",
        location: "CENTRAL BUSINESS DISTRICT",
        image: "https://yodezeen.com/wp-content/uploads/2025/03/Druskininkai_cam1-1024x512.jpg",
        status: "Pre-Launch",
      },
    ],
  },
  "urban-sprawl-co": {
    id: 2,
    name: "Urban Sprawl Co.",
    tagline: "Redefining Urban Living Spaces",
    heroImage: "https://yodezeen.com/wp-content/uploads/2025/03/WhatsApp-Image-2025-03-18-at-17.17.21-1024x731.jpeg",
    description:
      "Specializing in modern urban developments that blend contemporary design with functional living spaces.",
    completedProjects: 32,
    ongoingProjects: 6,
    yearsOfExperience: 12,
    currentProjects: [
      {
        name: "URBAN HEIGHTS",
        type: "2 BHK HOMES & RETAIL",
        location: "METRO STATION ROAD, PHASE 2",
        image: "https://yodezeen.com/wp-content/uploads/2025/03/WhatsApp-Image-2025-03-18-at-17.17.21-1024x731.jpeg",
        status: "Under Construction",
      },
      {
        name: "SPRAWL RESIDENCY",
        type: "1/2 BHK HOMES & RETAIL",
        location: "TECH PARK VICINITY, SECTOR 45",
        image: "https://yodezeen.com/wp-content/uploads/2025/02/KOZYN-171-1024x683.jpg",
        status: "Ready to Move",
      },
      {
        name: "URBAN PLAZA",
        type: "RETAIL & OFFICE SEGMENTS",
        location: "COMMERCIAL HUB, DOWNTOWN",
        image: "https://yodezeen.com/wp-content/uploads/2025/02/HOR-1024x576.jpg",
        status: "Under Construction",
      },
    ],
  },
  "vista-properties": {
    id: 3,
    name: "Vista Properties",
    tagline: "Panoramic Views, Premium Living",
    heroImage: "https://yodezeen.com/wp-content/uploads/2025/03/Druskininkai_cam1-1024x512.jpg",
    description:
      "Creating premium residential and commercial spaces with breathtaking views and world-class amenities.",
    completedProjects: 28,
    ongoingProjects: 5,
    yearsOfExperience: 10,
    currentProjects: [
      {
        name: "VISTA PANORAMA",
        type: "3/4 BHK LUXURY HOMES",
        location: "HILLSIDE AVENUE, PREMIUM SECTOR",
        image: "https://yodezeen.com/wp-content/uploads/2025/03/Druskininkai_cam1-1024x512.jpg",
        status: "Under Construction",
      },
      {
        name: "VISTA GARDENS",
        type: "2/3 BHK HOMES & RETAIL",
        location: "GARDEN CITY, PHASE 1",
        image: "https://yodezeen.com/wp-content/uploads/2024/11/living_CShading_LightMix_View040100-1024x724.jpg",
        status: "Launching Soon",
      },
      {
        name: "VISTA COMMERCIAL",
        type: "RETAIL COMPLEX",
        location: "MAIN BOULEVARD, CITY CENTER",
        image: "https://yodezeen.com/wp-content/uploads/2024/08/40000_Post-1024x724.jpg",
        status: "Pre-Launch",
      },
    ],
  },
  "zenith-developments": {
    id: 4,
    name: "Zenith Developments",
    tagline: "Reaching New Heights in Construction",
    heroImage: "https://yodezeen.com/wp-content/uploads/2025/02/KOZYN-171-1024x683.jpg",
    description:
      "Pioneering architectural excellence with innovative designs and cutting-edge construction technologies.",
    completedProjects: 38,
    ongoingProjects: 7,
    yearsOfExperience: 14,
    currentProjects: [
      {
        name: "ZENITH TOWERS",
        type: "4/5 BHK PREMIUM RESIDENCES",
        location: "SKYLINE DISTRICT, TOWER ROAD",
        image: "https://yodezeen.com/wp-content/uploads/2025/02/KOZYN-171-1024x683.jpg",
        status: "Under Construction",
      },
      {
        name: "ZENITH SQUARE",
        type: "2/3 BHK HOMES & RETAIL",
        location: "CENTRAL SQUARE, MAIN CITY",
        image: "https://yodezeen.com/wp-content/uploads/2025/02/HOR-1024x576.jpg",
        status: "Ready to Move",
      },
      {
        name: "ZENITH BUSINESS PARK",
        type: "OFFICE & RETAIL COMPLEX",
        location: "IT CORRIDOR, BUSINESS DISTRICT",
        image: "https://yodezeen.com/wp-content/uploads/2024/08/40000_Post-1024x724.jpg",
        status: "Under Construction",
      },
    ],
  },
  "skyline-ventures": {
    id: 5,
    name: "Skyline Ventures",
    tagline: "Touching the Sky, Grounded in Quality",
    heroImage: "https://yodezeen.com/wp-content/uploads/2025/02/HOR-1024x576.jpg",
    description:
      "Specializing in high-rise developments and luxury residential projects with unmatched quality standards.",
    completedProjects: 41,
    ongoingProjects: 9,
    yearsOfExperience: 16,
    currentProjects: [
      {
        name: "SKYLINE HEIGHTS",
        type: "3/4 BHK LUXURY APARTMENTS",
        location: "PREMIUM HEIGHTS, SECTOR 12",
        image: "https://yodezeen.com/wp-content/uploads/2025/02/HOR-1024x576.jpg",
        status: "Under Construction",
      },
      {
        name: "SKYLINE PLAZA",
        type: "2 BHK HOMES & RETAIL",
        location: "SHOPPING DISTRICT, PLAZA ROAD",
        image: "https://yodezeen.com/wp-content/uploads/2024/11/living_CShading_LightMix_View040100-1024x724.jpg",
        status: "Launching Soon",
      },
      {
        name: "SKYLINE CORPORATE",
        type: "OFFICE TOWERS",
        location: "FINANCIAL DISTRICT, TOWER AVENUE",
        image: "https://yodezeen.com/wp-content/uploads/2024/08/40000_Post-1024x724.jpg",
        status: "Pre-Launch",
      },
    ],
  },
  "harmony-homes-inc": {
    id: 6,
    name: "Harmony Homes Inc.",
    tagline: "Where Comfort Meets Elegance",
    heroImage: "https://yodezeen.com/wp-content/uploads/2024/11/living_CShading_LightMix_View040100-1024x724.jpg",
    description: "Creating harmonious living spaces that blend comfort, style, and functionality for modern families.",
    completedProjects: 35,
    ongoingProjects: 6,
    yearsOfExperience: 13,
    currentProjects: [
      {
        name: "HARMONY GARDENS",
        type: "2/3 BHK FAMILY HOMES",
        location: "GARDEN VALLEY, RESIDENTIAL ZONE",
        image: "https://yodezeen.com/wp-content/uploads/2024/11/living_CShading_LightMix_View040100-1024x724.jpg",
        status: "Under Construction",
      },
      {
        name: "HARMONY SQUARE",
        type: "1/2 BHK HOMES & RETAIL",
        location: "COMMUNITY CENTER, PHASE 3",
        image: "https://yodezeen.com/wp-content/uploads/2024/09/12443-1024x576.jpg",
        status: "Ready to Move",
      },
      {
        name: "HARMONY LIFESTYLE",
        type: "3/4 BHK PREMIUM HOMES",
        location: "LIFESTYLE DISTRICT, PREMIUM AREA",
        image: "https://yodezeen.com/wp-content/uploads/2024/08/living_CShading_LightMix_View010100-1024x724.jpg",
        status: "Launching Soon",
      },
    ],
  },
  "greenland-estates": {
    id: 7,
    name: "Greenland Estates",
    tagline: "Green Living, Sustainable Future",
    heroImage: "https://yodezeen.com/wp-content/uploads/2024/09/12443-1024x576.jpg",
    description: "Committed to sustainable development with eco-friendly designs and green building practices.",
    completedProjects: 29,
    ongoingProjects: 5,
    yearsOfExperience: 11,
    currentProjects: [
      {
        name: "GREENLAND VILLAS",
        type: "3/4 BHK INDEPENDENT VILLAS",
        location: "GREEN BELT AREA, VILLA ROAD",
        image: "https://yodezeen.com/wp-content/uploads/2024/09/12443-1024x576.jpg",
        status: "Under Construction",
      },
      {
        name: "GREENLAND APARTMENTS",
        type: "2/3 BHK ECO HOMES",
        location: "ECO PARK VICINITY, GREEN SECTOR",
        image: "https://yodezeen.com/wp-content/uploads/2024/08/living_CShading_LightMix_View010100-1024x724.jpg",
        status: "Launching Soon",
      },
      {
        name: "GREENLAND COMMERCIAL",
        type: "GREEN OFFICE COMPLEX",
        location: "SUSTAINABLE BUSINESS PARK",
        image: "https://yodezeen.com/wp-content/uploads/2024/08/40000_Post-1024x724.jpg",
        status: "Pre-Launch",
      },
    ],
  },
  "corporate-hub-ltd": {
    id: 8,
    name: "Corporate Hub Ltd.",
    tagline: "Building Business Excellence",
    heroImage: "https://yodezeen.com/wp-content/uploads/2024/08/40000_Post-1024x724.jpg",
    description: "Specializing in commercial developments and corporate spaces that drive business success.",
    completedProjects: 42,
    ongoingProjects: 8,
    yearsOfExperience: 17,
    currentProjects: [
      {
        name: "CORPORATE TOWERS",
        type: "OFFICE & RETAIL COMPLEX",
        location: "BUSINESS DISTRICT, CORPORATE ROAD",
        image: "https://yodezeen.com/wp-content/uploads/2024/08/40000_Post-1024x724.jpg",
        status: "Under Construction",
      },
      {
        name: "HUB RESIDENCES",
        type: "2/3 BHK SERVICE APARTMENTS",
        location: "NEAR IT PARK, EXECUTIVE AREA",
        image: "https://yodezeen.com/wp-content/uploads/2024/08/living_CShading_LightMix_View010100-1024x724.jpg",
        status: "Ready to Move",
      },
      {
        name: "CORPORATE PLAZA",
        type: "MIXED USE DEVELOPMENT",
        location: "CENTRAL BUSINESS DISTRICT",
        image: "https://yodezeen.com/wp-content/uploads/2024/11/living_CShading_LightMix_View040100-1024x724.jpg",
        status: "Launching Soon",
      },
    ],
  },
  "pristine-living": {
    id: 9,
    name: "Pristine Living",
    tagline: "Pure Luxury, Perfect Homes",
    heroImage: "https://yodezeen.com/wp-content/uploads/2024/08/living_CShading_LightMix_View010100-1024x724.jpg",
    description: "Creating pristine living environments with attention to detail and luxury finishes.",
    completedProjects: 31,
    ongoingProjects: 6,
    yearsOfExperience: 12,
    currentProjects: [
      {
        name: "PRISTINE HEIGHTS",
        type: "3/4 BHK LUXURY APARTMENTS",
        location: "LUXURY DISTRICT, HEIGHTS ROAD",
        image: "https://yodezeen.com/wp-content/uploads/2024/08/living_CShading_LightMix_View010100-1024x724.jpg",
        status: "Under Construction",
      },
      {
        name: "PRISTINE GARDENS",
        type: "2/3 BHK GARDEN HOMES",
        location: "BOTANICAL GARDEN AREA, SECTOR 8",
        image:
          "https://yodezeen.com/wp-content/uploads/2024/07/%D0%97%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%BD%D1%8F-1024x576.png",
        status: "Launching Soon",
      },
      {
        name: "PRISTINE COMMERCIAL",
        type: "RETAIL & OFFICE SPACES",
        location: "COMMERCIAL ZONE, MAIN STREET",
        image: "https://yodezeen.com/wp-content/uploads/2024/08/40000_Post-1024x724.jpg",
        status: "Pre-Launch",
      },
    ],
  },
  "elite-residences": {
    id: 10,
    name: "Elite Residences",
    tagline: "Exclusive Living, Exceptional Quality",
    heroImage: "https://yodezeen.com/wp-content/uploads/2024/08/Untitled-14444444-1024x576.png",
    description:
      "Developing exclusive residential projects for discerning clients who demand the finest in luxury living.",
    completedProjects: 26,
    ongoingProjects: 4,
    yearsOfExperience: 9,
    currentProjects: [
      {
        name: "ELITE MANSIONS",
        type: "4/5 BHK LUXURY VILLAS",
        location: "ELITE ENCLAVE, MANSION ROAD",
        image: "https://yodezeen.com/wp-content/uploads/2024/08/Untitled-14444444-1024x576.png",
        status: "Under Construction",
      },
      {
        name: "ELITE TOWERS",
        type: "3/4 BHK PENTHOUSE APARTMENTS",
        location: "PREMIUM TOWERS, ELITE DISTRICT",
        image: "https://yodezeen.com/wp-content/uploads/2025/02/HOR-1024x576.jpg",
        status: "Launching Soon",
      },
      {
        name: "ELITE LIFESTYLE",
        type: "LUXURY RETAIL & DINING",
        location: "LIFESTYLE BOULEVARD, CITY CENTER",
        image: "https://yodezeen.com/wp-content/uploads/2024/08/40000_Post-1024x724.jpg",
        status: "Pre-Launch",
      },
    ],
  },
  "minimalist-builds": {
    id: 11,
    name: "Minimalist Builds",
    tagline: "Less is More, Quality is Everything",
    heroImage: "https://yodezeen.com/wp-content/uploads/2024/06/WhatsApp-Image-2024-06-07-at-11.34.06-1024x819.jpeg",
    description:
      "Embracing minimalist design principles to create clean, functional, and aesthetically pleasing spaces.",
    completedProjects: 33,
    ongoingProjects: 7,
    yearsOfExperience: 13,
    currentProjects: [
      {
        name: "MINIMAL HOMES",
        type: "2/3 BHK CONTEMPORARY APARTMENTS",
        location: "DESIGN DISTRICT, MINIMAL STREET",
        image: "https://yodezeen.com/wp-content/uploads/2024/06/WhatsApp-Image-2024-06-07-at-11.34.06-1024x819.jpeg",
        status: "Under Construction",
      },
      {
        name: "MINIMAL STUDIOS",
        type: "1/2 BHK STUDIO APARTMENTS",
        location: "ARTIST QUARTER, STUDIO LANE",
        image: "https://yodezeen.com/wp-content/uploads/2024/09/12443-1024x576.jpg",
        status: "Ready to Move",
      },
      {
        name: "MINIMAL WORKSPACE",
        type: "MODERN OFFICE SPACES",
        location: "CREATIVE DISTRICT, WORKSPACE AVENUE",
        image: "https://yodezeen.com/wp-content/uploads/2024/08/40000_Post-1024x724.jpg",
        status: "Launching Soon",
      },
    ],
  },
  "garden-homes-co": {
    id: 12,
    name: "Garden Homes Co.",
    tagline: "Where Nature Meets Architecture",
    heroImage:
      "https://yodezeen.com/wp-content/uploads/2024/07/%D0%97%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%BD%D1%8F-1024x576.png",
    description:
      "Creating homes that seamlessly blend with nature, featuring beautiful gardens and sustainable landscaping.",
    completedProjects: 37,
    ongoingProjects: 8,
    yearsOfExperience: 15,
    currentProjects: [
      {
        name: "GARDEN PARADISE",
        type: "3/4 BHK GARDEN VILLAS",
        location: "BOTANICAL GARDENS, PARADISE ROAD",
        image:
          "https://yodezeen.com/wp-content/uploads/2024/07/%D0%97%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%BD%D1%8F-1024x576.png",
        status: "Under Construction",
      },
      {
        name: "GARDEN COURT",
        type: "2/3 BHK COURTYARD HOMES",
        location: "GREEN VALLEY, COURT STREET",
        image: "https://yodezeen.com/wp-content/uploads/2024/11/living_CShading_LightMix_View040100-1024x724.jpg",
        status: "Launching Soon",
      },
      {
        name: "GARDEN RETREAT",
        type: "WELLNESS & RETAIL COMPLEX",
        location: "NATURE PARK, RETREAT AVENUE",
        image: "https://yodezeen.com/wp-content/uploads/2024/08/living_CShading_LightMix_View010100-1024x724.jpg",
        status: "Pre-Launch",
      },
    ],
  },
};
'export type BuilderData = (typeof builderData)[keyof typeof builderData]' 